import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './GlobalRedux/provider'
import 'typeface-open-sans';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{fontFamily: "Open Sans, sans-serif"}} className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
